export const allAreasMusic = [
  { value: "Apple Music", label: "Apple Music" },
  { value: "7digital", label: "7digital" },
  { value: "ACRCloud", label: "ACRCloud" },
  { value: "Amazon", label: "Amazon" },
  { value: "Anghami", label: "Anghami" },
  { value: "AudibleMagic", label: "AudibleMagic" },
  { value: "AWA", label: "AWA" },
  { value: "BASE_NDA", label: "BASE_NDA" },
  { value: "BoomPlay", label: "BoomPlay" },
  { value: "CapCut", label: "CapCut" },
  { value: "ClicknClear", label: "ClicknClear" },
  { value: "Cron Telecom", label: "Cron Telecom" },
  { value: "Deezer", label: "Deezer" },
  { value: "FLO", label: "FLO" },
  { value: "FonMix", label: "FonMix" },
  { value: "GoMusic", label: "GoMusic" },
  { value: "hitter", label: "hitter" },
  { value: "iHeart", label: "iHeart" },
  { value: "Jaxsta", label: "Jaxsta" },
  { value: "JioSaavn", label: "JioSaavn" },
  { value: "Kanjian", label: "Kanjian" },
  { value: "KKBOX", label: "KKBOX" },
  { value: "Likee", label: "Likee" },
  { value: "LINE", label: "LINE" },
  { value: "LyricFind", label: "LyricFind" },
  { value: "Mixcloud", label: "Mixcloud" },
  { value: "MobiMusic (Казахстан)", label: "MobiMusic (Казахстан)" },
  { value: "MusixMatch", label: "MusixMatch" },
  { value: "Muztube", label: "Muztube" },
  { value: "Netease", label: "Netease" },
  { value: "Pandora", label: "Pandora" },
  { value: "Peloton", label: "Peloton" },
  { value: "Presto", label: "Presto" },
  { value: "Pretzel", label: "Pretzel" },
  { value: "Qishui Yinyue", label: "Qishui Yinyue" },
  { value: "Qobuz", label: "Qobuz" },
  { value: "Slacker", label: "Slacker" },
  { value: "Smule", label: "Smule" },
  { value: "SoundCloud", label: "SoundCloud" },
  { value: "SoundExchange", label: "SoundExchange" },
  { value: "Spotify", label: "Spotify" },
  { value: "Tencent", label: "Tencent" },
  { value: "TIDAL", label: "TIDAL" },
  { value: "TikTok", label: "TikTok" },
  { value: "TikTok Music Video", label: "TikTok Music Video" },
  { value: "TREBEL", label: "TREBEL" },
  { value: "VK Музыка", label: "VK Музыка" },
  { value: "Yappy", label: "Yappy" },
  { value: "YouTube Copyright", label: "YouTube Copyright" },
  { value: "YouTube Music", label: "YouTube Music" },
  { value: "YouTube (Sound Recording)", label: "YouTube (Sound Recording)" },
  { value: "Билайн, Теле2 (РБТ)", label: "Билайн, Теле2 (РБТ)" },
  { value: "ВКонтакте Видео", label: "ВКонтакте Видео" },
  { value: "Звук", label: "Звук" },
];
