export const allGenres = [
  { value: "EDM", label: "EDM" },
  { value: "K-Pop", label: "K-Pop" },
  { value: "R&B", label: "R&B" },
  { value: "Akademicheskaya muzyka", label: "Академическая музыка" },
  { value: "Akusticheskaya muzyka", label: "Акустическая музыка" },
  { value: "Alternativa", label: "Альтернатива" },
  { value: "Alternativnyy R&B", label: "Альтернативный R&B" },
  { value: "Alternativnyy metal", label: "Альтернативный метал" },
  { value: "Alternativnyy rok", label: "Альтернативный рок" },
  { value: "Alternativnyy khip-khop", label: "Альтернативный хип-хоп" },
  { value: "Andergraund", label: "Андерграунд" },
  { value: "Audioknigi", label: "Аудиокниги" },
  { value: "Barokko-pop", label: "Барокко-поп" },
  { value: "Blyuz", label: "Блюз" },
  { value: "Blyuz-rok", label: "Блюз-рок" },
  { value: "Brit-pop", label: "Брит-поп" },
  { value: "Giperpop", label: "Гиперпоп" },
  { value: "Glem-metal", label: "Глэм-метал" },
  { value: "Glem-rok", label: "Глэм-рок" },
  { value: "Gospel", label: "Госпел" },
  { value: "Granzh", label: "Гранж" },
  { value: "Detskaya muzyka", label: "Детская музыка" },
  { value: "Dzhaz", label: "Джаз" },
  { value: "Dzhaz-fank", label: "Джаз-фанк" },
  { value: "Didzhey-miksy", label: "Диджей-миксы" },
  { value: "Dip-khaus", label: "Дип-хаус" },
  { value: "Disko", label: "Диско" },
  { value: "Drill", label: "Дрилл" },
  { value: "Drim-pop", label: "Дрим-поп" },
  { value: "Zhivaya muzyka", label: "Живая музыка" },
  { value: "Zvukovyye effekty", label: "Звуковые эффекты" },
  { value: "Indastrial", label: "Индастриал" },
  { value: "Indi", label: "Инди" },
  { value: "Indi-rok", label: "Инди-рок" },
  { value: "Instrumental", label: "Инструментал" },
  { value: "Kavery", label: "Каверы" },
  { value: "Kaliannyy rep", label: "Кальянный рэп" },
  { value: "Kamernaya muzyka", label: "Камерная музыка" },
  { value: "Kantri", label: "Кантри" },
  { value: "Kantri-rok", label: "Кантри-рок" },
  { value: "Klassicheskaya muzyka", label: "Классическая музыка" },
  { value: "Latinskiy pop", label: "Латинский поп" },
  { value: "Launzh", label: "Лаунж" },
  { value: "Lou-fay", label: "Лоу-фай" },
  { value: "Metal", label: "Метал" },
  { value: "Myuzikl", label: "Мюзикл" },
  { value: "Neoklassika", label: "Неоклассика" },
  { value: "Nyu-veyv", label: "Нью-вейв" },
  { value: "Pank-rok", label: "Панк-рок" },
  { value: "Podkasty", label: "Подкасты" },
  { value: "Pop-muzyka", label: "Поп-музыка" },
  { value: "Pop-pank", label: "Поп-панк" },
  { value: "Pop-rok", label: "Поп-рок" },
  { value: "Post-pank", label: "Пост-панк" },
  { value: "Post-rok", label: "Пост-рок" },
  { value: "Psikhodelika", label: "Психоделика" },
  { value: "Reggi", label: "Регги" },
  { value: "Ritm-end-blyuz", label: "Ритм-энд-блюз" },
  { value: "Rok", label: "Рок" },
  { value: "Rok-n-roll", label: "Рок-н-ролл" },
  { value: "Rokabilli", label: "Рокабилли" },
  { value: "Russkiy rok", label: "Русский рок" },
  { value: "Russkiy rep", label: "Русский рэп" },
  { value: "Russkiy shanson", label: "Русский шансон" },
  { value: "Rep", label: "Рэп" },
  { value: "Rep-battl", label: "Рэп-баттл" },
  { value: "Saundtreki", label: "Саундтреки" },
  { value: "Simfonicheskaya muzyka", label: "Симфоническая музыка" },
  { value: "Sintveyv", label: "Синтвейв" },
  { value: "Sinti-pop", label: "Синти-поп" },
  { value: "Sovetskaya estrada", label: "Советская эстрада" },
  { value: "Soul", label: "Соул" },
  { value: "Tantsevalnaya muzyka", label: "Танцевальная музыка" },
  { value: "Tekhno", label: "Техно" },
  { value: "Trans", label: "Транс" },
  { value: "Trip-khop", label: "Трип-хоп" },
  { value: "Trep", label: "Трэп" },
  { value: "Fank", label: "Фанк" },
  { value: "Folk", label: "Фолк" },
  { value: "Fonk", label: "Фонк" },
  { value: "Fristayl", label: "Фристайл" },
  { value: "Fyuzhn", label: "Фьюжн" },
  { value: "Khard-rok", label: "Хард-рок" },
  { value: "Khardkor", label: "Хардкор" },
  { value: "Khaus", label: "Хаус" },
  { value: "Khevi-metal", label: "Хеви-метал" },
  { value: "Khip-khop", label: "Хип-хоп" },
  { value: "Chikago-blyuz", label: "Чикаго-блюз" },
  { value: "Shanson", label: "Шансон" },
  { value: "Eksperimentalnaya muzyka", label: "Экспериментальная музыка" },
  { value: "Elektro-khaus", label: "Электро-хаус" },
  { value: "Elektronika", label: "Электроника" },
  { value: "Embiyent", label: "Эмбиент" },
  { value: "Emo", label: "Эмо" },
  { value: "Emo-rep", label: "Эмо-рэп" },
  { value: "Etnicheskaya muzyka", label: "Этническая музыка" },
];
