import Image from 'next/image';
import type { Metadata } from 'next';
import '../../globals.css';
import SideBarProvider from '@/providers/SideBar.provider';
import SideBar from '@/components/Layout/SideBar/SideBar';
import { Suspense } from 'react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className='h-full bg-[var(--background)]'>
			<Image
				className='fixed bottom-0 pointer-events-none'
				src='/assets/BG/docs-left.png'
				alt='dots1'
				draggable='false'
				width={550}
				height={550}
			/>
			<Image
				className='fixed right-0 aspect-square w-1/3 pointer-events-none'
				src='/assets/BG/docs-right.png'
				alt='dots2'
				draggable='false'
				width={550}
				height={550}
			/>
			<SideBarProvider>
				<SideBar>
					<Suspense>{children}</Suspense>
				</SideBar>
			</SideBarProvider>
		</main>
	);
}
