services:
  icecream-backend:
    container_name: icecream_backend
    image: icecream-backend:latest
    environment:
      #DB
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:?error}
      DB_NAME: ${DB_NAME:?error}
      #AUTH
      SALT_ROUNDS: ${SALT_ROUNDS:?error}
      #S3
      S3_HOST: ${S3_HOST:?error}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:?error}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?error}
      S3_USE_SSL: ${S3_USE_SSL:?error}
      NEXT_PUBLIC_S3_URL: ${NEXT_PUBLIC_S3_URL:?error}
      #YOOKASSA
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID:?error}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY:?error}
      #NEXT
      NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN:?error}
      #BACKEND
      SHOW_API_DOCS: ${SHOW_API_DOCS:?error}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - icecream
    depends_on:
      - minio
      - postgres
  icecream-frontend:
    container_name: icecream_frontend
    image: icecream-frontend:latest
    environment:
      #AUTH
      SALT_ROUNDS: ${SALT_ROUNDS:?error}
      AUTH_VK_ID: ${AUTH_VK_ID:?error}
      AUTH_VK_SECRET: ${AUTH_VK_SECRET:?error}
      AUTH_VK_SERVICE: ${AUTH_VK_SERVICE:?error}
      AUTH_YANDEX_ID: ${AUTH_YANDEX_ID:?error}
      AUTH_YANDEX_SECRET: ${AUTH_YANDEX_SECRET:?error}
      #SMTP
      SMTP_HOST: ${SMTP_HOST:?error}
      SMTP_PORT: ${SMTP_PORT:?error}
      SMTP_SECURE: ${SMTP_SECURE:?error}
      SMTP_USER: ${SMTP_USER:?error}
      SMTP_PASSWORD: ${SMTP_PASSWORD:?error}
      #S3
      NEXT_PUBLIC_S3_URL: ${NEXT_PUBLIC_S3_URL:?error}
      #FRONTEND
      NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN:?error}
      #YOOKASSA
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID:?error}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY:?error}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - icecream
    depends_on:
      - postgres
      - minio
    volumes:
      - ./apps/frontend/public:./app/public
    # ports:
    #   - "3000:3000"
  migration_tool:
    container_name: icecream_migration_tool
    image: icecream-migration-tool:latest
    environment:
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:?error}
      DB_NAME: ${DB_NAME:?error}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - icecream
  minio: #port 9000
    container_name: icecream_s3
    image: minio/minio
    volumes:
      - icecream_s3:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?error}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
      MINIO_BROWSER_REDIRECT: false
    env_file:
      - .env
    command: server --console-address ":9001" /data
    networks:
      - icecream
    restart: unless-stopped
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
  postgres: #port 5432
    container_name: icecream_data
    image: postgres:16.4-bullseye
    environment:
      POSTGRES_USER: ${DB_USER:?error}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?error}
      PGDATA: ${PGDATA:?error}
    env_file:
      - .env
    volumes:
      - icecream_postgres:${PGDATA:?error}
    networks:
      - icecream
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
  pgadmin:
    container_name: icecream_db_admin
    image: elestio/pgadmin:REL-8_12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?error}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?error}
      PGADMIN_LISTEN_PORT: 5050
    env_file:
      - .env
    volumes:
      - icecream_pgadmin:/var/lib/pgadmin
    networks:
      - icecream
    restart: always
    depends_on:
      - postgres
    # ports:
    #   - "5050:5050"
  proxy_manager:
    container_name: icecream_proxy
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - icecream
    restart: unless-stopped

volumes:
  icecream_s3:
  icecream_postgres:
  icecream_pgadmin:

networks:
  icecream:
    driver: bridge
