import style from './layout.module.css';
import '../globals.css';
import CanvasThree from '@/entities/CanvasThree/CanvasThree';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<main className={style.main}>
					<div className={style.view}>
						<CanvasThree />
					</div>
					<div className={style.form}>{children}</div>
				</main>
			</body>
		</html>
	);
}
