import { authRedirect } from "@/actions/auth";
import { roboto } from "@/fonts";
import { PropsWithChildren } from "react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  await authRedirect();

  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
