import { roboto } from "@/fonts";
import { PropsWithChildren, Suspense } from "react";
import "./globals.css";
import "./static.css";
import dynamic from "next/dynamic";
import { cookies } from "next/headers";
import Loading from "./loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const AppThemeProvider = dynamic(() => import("../providers/ThemeContext"), {
    ssr: false,
  });

  const theme = cookies().get("__theme__")?.value || "system";

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
