import BreadCrumbs from "@/entities/BreadCrumbs/BreadCrumbs";
import Header from "@/entities/Header/Header";
import Sidebar from "@/entities/Sidebar/Sidebar";
import { open } from "@/fonts";
import { SidebarContextProvider } from "@/providers/SidebarContext";
import classNames from "classnames";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { cookies } from "next/headers";
import { PropsWithChildren } from "react";
import style from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CabinetLayout({ children }: PropsWithChildren) {
  const AppThemeProvider = dynamic(() => import("@/providers/ThemeContext"), {
    ssr: false,
  });

  const theme = cookies().get("__theme__")?.value || "system";

  return (
    <AppThemeProvider attribute="data-theme" defaultTheme={theme} enableSystem>
      <SidebarContextProvider>
        <main className={classNames(style.main, open.className)}>
          <div className={style.row}>
            <Sidebar />
            <div className={style.col}>
              <Header />
              <div className={style.content}>
                <BreadCrumbs home="Панель управления" />
                {children}
              </div>
            </div>
          </div>
        </main>
      </SidebarContextProvider>
    </AppThemeProvider>
  );
}
