import Sidebar from "@/entities/Sidebar/Sidebar";
import { SidebarContextProvider } from "@/providers/SidebarContext";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { cookies } from "next/headers";
import style from "./layout.module.css";
import { open } from "@/fonts";
import classNames from "classnames";
import Header from "@/entities/Header/Header";
import BreadCrumbs from "@/entities/BreadCrumbs/BreadCrumbs";
import MyTitle from "@/shared/MyTitle/MyTitle";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const AppThemeProvider = dynamic(
    () => import("../../providers/ThemeContext"),
    {
      ssr: false,
    }
  );

  const theme = cookies().get("__theme__")?.value || "system";

  return (
    <div className={style.bg}>
      <AppThemeProvider
        attribute="data-theme"
        defaultTheme={theme}
        enableSystem
      >
        <SidebarContextProvider>
          <main className={classNames(style.main, open.className)}>
            <div className={style.row}>
              <Sidebar />
              <div className={style.col}>
                <Header />
                <div className="content">
                  <BreadCrumbs />
                  {children}
                </div>
              </div>
            </div>
          </main>
        </SidebarContextProvider>
      </AppThemeProvider>
    </div>
  );
}
