import { getFullUrl } from "@/actions/url";
import CanvasThree from "@/entities/CanvasThree/CanvasThree";
import style from "./layout.module.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUrl = await getFullUrl();

  return (
    <main className={style.main}>
      <div className={style.view}>
        <CanvasThree />
      </div>
      <div className={style.form}>{children}</div>
    </main>
  );
}
