import style from "./layout.module.css";
import CanvasThree from "@/entities/CanvasThree/CanvasThree";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={style.main}>
      <div className={style.view}>
        <CanvasThree />
      </div>
      <div className={style.form}>{children}</div>
    </main>
  );
}
