import type { Metadata } from "next";
import Sidebar from "@/entities/Sidebar/Sidebar";
import { SidebarContextProvider } from "@/providers/SidebarContext";
import { PageTransitionProvider } from "@/providers/PageTransitionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarContextProvider>
      <main className="main">
        <Sidebar />
        <PageTransitionProvider className="content">
          {children}
        </PageTransitionProvider>
      </main>
    </SidebarContextProvider>
  );
}
