import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import '../globals.css';
import Sidebar from '@/entities/Sidebar/Sidebar';
import { SidebarContextProvider } from '@/context/SidebarContext';

const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<SidebarContextProvider>
					<main className={'main'}>
						<Sidebar />
						<div className='content'>{children}</div>
					</main>
				</SidebarContextProvider>
			</body>
		</html>
	);
}
